Default: &defaults
  database: ttt-yesod124.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ttt-yesod124_test.sqlite3
  <<: *defaults

Staging:
  database: ttt-yesod124_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ttt-yesod124_production.sqlite3
  poolsize: 100
  <<: *defaults
